apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x4ve
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-x4ve@sha256:0140e3186490eff5b4a9b3e10d5562f640b437584b494167c3ce825cec7a718b
        name: my-nodejs
        resources: {}
status: {}
